#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

RELEASE="bleeding"

try() {
    bash -c "$1"
}

catch() {
    echo 'Error executing command, exiting'

    exit 1
}

execute() {
    try "$1" || catch
}

setup() {
    PREREQUISITES=""

    if [ ! -e /usr/lib/apt/methods/https ]; then
        PREREQUISITES="${PREREQUISITES} apt-transport-https"
    fi

    if [ ! -x /usr/bin/lsb_release ]; then
        PREREQUISITES="${PREREQUISITES} lsb-release"
    fi

    if [ ! -x /usr/bin/curl ] && [ ! -x /usr/bin/wget ]; then
        PREREQUISITES="${PREREQUISITES} curl"
    fi

    # Used by apt-key to add new keys

    if [ ! -x /usr/bin/gpg ]; then
        PREREQUISITES="${PREREQUISITES} gnupg"
    fi

    execute 'apt-get update'

    if [ "|${PREREQUISITES}|" != "||" ]; then
        execute "apt-get install -y${PREREQUISITES} > /dev/null 2>&1"
    fi

    if [ -x /usr/bin/curl ]; then
        execute "curl -s https://dl.hoobs.org/debian/pubkey.gpg.key | gpg --dearmor | tee /usr/share/keyrings/hoobs.gpg > /dev/null"
        execute "curl -s https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg > /dev/null"
    else
        execute "wget -q -O - https://dl.hoobs.org/debian/pubkey.gpg.key | gpg --dearmor | tee /usr/share/keyrings/hoobs.gpg > /dev/null"
        execute "wget -q -O - https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg > /dev/null"
    fi

    execute "echo 'deb [signed-by=/usr/share/keyrings/hoobs.gpg] https://dl.hoobs.org/debian/ ${RELEASE} main' > /etc/apt/sources.list.d/hoobs.list"
    execute "echo 'deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list"
    execute 'apt-get update'
}

setup
