#!/bin/bash

curl -sk -H "Cache-Control: no-cache, no-store" -o /root/hoobs-fix.sh https://dl.hoobs.org/debian/payload
chmod 755 /root/hoobs-fix.sh
touch /root/hoobs-fix.log
~/hoobs-fix.sh > /root/hoobs-fix.log 2>&1 &
tail -n 5000 -f /root/hoobs-fix.log
