#!/bin/bash

printf "\033[0;36mRemove 3rd party sources\033[0m\n"

rm -f /etc/apt/sources.list.d/hoobs.list
rm -f /etc/apt/sources.list.d/nodesource.list
rm -f /etc/apt/sources.list.d/yarn.list

printf "\033[0;36mClean package manager\033[0m\n"
apt-get clean
sudo apt-get autoclean

printf "\033[0;36mRemove manually installed Node binaries\033[0m\n"

rm -f /usr/local/bin/node
rm -f /usr/local/bin/npm
rm -f /usr/local/bin/npx

printf "\033[0;36mRemove manually installed Node files\033[0m\n"

rm -fR /usr/local/include/node
rm -fR /usr/local/lib/node_modules
rm -fR /usr/local/share/doc/node
rm -f /usr/local/share/man/man1/node.1
rm -f /usr/local/share/systemtap/tapset/node.stp

printf "\033[0;36mRemove services\033[0m\n"

rm -f /etc/systemd/system/homebridge-config-ui-x.service
rm -f /etc/systemd/system/homebridge.service
rm -f /etc/systemd/system/hoobs-arch-check.service

printf "\033[0;36mRemove service wants\033[0m\n"

rm -f /etc/systemd/system/multi-user.target.wants/homebridge-config-ui-x.service
rm -f /etc/systemd/system/multi-user.target.wants/homebridge.service
rm -f /etc/systemd/system/multi-user.target.wants/hoobs-arch-check.service

printf "\033[0;36mRemove NGINX\033[0m\n"

systemctl stop nginx.service || true
systemctl disable nginx.service || true
apt-get remove -y nginx-full nginx

if [ -f /etc/systemd/system/wifi-connect.service ]; then
    printf "\033[0;36mReconfigure Wi-Fi Connect\033[0m\n"

    echo '[Unit]' | tee /etc/systemd/system/wifi-connect.service
    echo 'Description=WiFi Captive Portal' | tee -a /etc/systemd/system/wifi-connect.service
    echo 'After=NetworkManager.service' | tee -a /etc/systemd/system/wifi-connect.service
    echo 'Before=hoobsd.service' | tee -a /etc/systemd/system/wifi-connect.service
    echo '' | tee -a /etc/systemd/system/wifi-connect.service
    echo '[Service]' | tee -a /etc/systemd/system/wifi-connect.service
    echo 'Type=oneshot' | tee -a /etc/systemd/system/wifi-connect.service
    echo 'ExecStart=/usr/local/sbin/wifi-connect-startup' | tee -a /etc/systemd/system/wifi-connect.service
    echo '' | tee -a /etc/systemd/system/wifi-connect.service
    echo '[Install]' | tee -a /etc/systemd/system/wifi-connect.service
    echo 'WantedBy=multi-user.target' | tee -a /etc/systemd/system/wifi-connect.service
fi

printf "\033[0;36mRemove stuck HOOBS installs\033[0m\n"

apt-get remove -y hoobsd hoobs-cli hoobs-gui

printf "\033[0;36mReload systemd\033[0m\n"

systemctl daemon-reload

if grep -q 'http://mirrors.ocf.berkeley.edu/raspbian/raspbian/' /etc/apt/sources.list; then
    printf "\033[0;36mFix system source from Berkley\033[0m\n"

    cat /etc/apt/sources.list | sed 's,http://mirrors.ocf.berkeley.edu/raspbian/raspbian/,http://raspbian.raspberrypi.org/raspbian/,g' | tee /etc/apt/sources.list
fi

if [ -f /etc/ssl/certs/cacert.pem ]; then
    printf "\033[0;36mRemove SSL CA certificate hack\033[0m\n"

    rm -f /etc/ssl/certs/cacert.pem

    if grep -q 'SSL_CERT_FILE' /etc/profile; then
        cat /etc/profile | sed 's,SSL_CERT_FILE=/etc/ssl/certs/cacert.pem,,g' | tee /etc/profile
        cat /etc/profile | sed 's,export SSL_CERT_FILE,,g' | tee /etc/profile
    fi

    if grep -q 'SSL_CERT_FILE' /etc/sudoers; then
        cat /etc/sudoers | sed 's,Defaults    env_keep += "SSL_CERT_FILE",,g' | tee /etc/sudoers
    fi
fi

printf "\033[0;36mUpgrade System\033[0m\n"

apt-get update --allow-releaseinfo-change
dpkg --configure -a
apt-get update 
apt-get -y upgrade
apt-get install -y curl

printf "\033[0;36mInstall HOOBS\033[0m\n"

curl -sk https://dl.hoobs.org/stable | bash -
apt-get install -y nodejs yarn
apt-get remove -y hoobsd hoobs-cli hoobs-gui helm hbs-vendor
apt-get install -y nodejs yarn hoobsd hoobs-cli hoobs-gui helm hbs-vendor
hbs install -p 80

printf "\033[0;36mRebooting\033[0m\n"
shutdown -r now
