#!/bin/bash

message() {
	local tmp=""

	[[ -n $2 ]] && tmp="[\e[0;33m $2 \x1B[0m]"

	case $3 in
		wrn)
			echo -e "[\e[0;35m warn \x1B[0m] $1 $tmp"
			;;

		info)
            echo -e "[\e[0;32m .... \x1B[0m] $1 $tmp"
			;;

		*)
			echo -e "[\e[0;32m o.k. \x1B[0m] $1 $tmp"
			;;
	esac
}

clean_sources() {
    message "removing mal-configured sources" "hoobs, nodesource, yarn" "info"

    rm -f /etc/apt/sources.list.d/hoobs.list
    rm -f /etc/apt/sources.list.d/nodesource.list
    rm -f /etc/apt/sources.list.d/yarn.list

    message "purging stuck installs" "" "info"

    dpkg --purge --force-all hoobsd hoobs-cli hoobs-gui

    message "removing queued pre and post install scripts" "" "info"

    rm -fR /var/lib/dpkg/updates/*
    rm -fR /var/lib/dpkg/info/hoobsd*
    rm -fR /var/lib/dpkg/info/hoobs-cli*
    rm -fR /var/lib/dpkg/info/hoobs-gui*

    message "cleaning package manager" "" "info"

    apt-get clean
    apt-get autoclean

    message "sources cleaned" "" "ok"
}

clean_node_installs() {
    message "removing installed node binaries" "node, npm, npx" "info"

    rm -f /usr/local/bin/node
    rm -f /usr/local/bin/npm
    rm -f /usr/local/bin/npx

    message "removing node support files" "" "info"

    rm -fR /usr/local/include/node
    rm -fR /usr/local/lib/node_modules
    rm -fR /usr/local/share/doc/node
    rm -f /usr/local/share/man/man1/node.1
    rm -f /usr/local/share/systemtap/tapset/node.stp

    message "node cleaned" "" "ok"
}

clean_old_services() {
    message "removing services" "hoobs, homebridge, ui-x" "info"

    rm -f /etc/systemd/system/homebridge-config-ui-x.service
    rm -f /etc/systemd/system/homebridge.service
    rm -f /etc/systemd/system/hoobs-arch-check.service

    message "disabling services" "" "info"

    rm -f /etc/systemd/system/multi-user.target.wants/homebridge-config-ui-x.service
    rm -f /etc/systemd/system/multi-user.target.wants/homebridge.service
    rm -f /etc/systemd/system/multi-user.target.wants/hoobs-arch-check.service

    message "removing conflicting packages" "nginx" "info"

    systemctl stop nginx.service || true
    systemctl disable nginx.service || true
    apt-get remove -y nginx-full nginx

    if [ -f /etc/systemd/system/wifi-connect.service ]; then
        message "repairing wifi captive portal" "wifi-connect" "info"

        echo '[Unit]' | tee /etc/systemd/system/wifi-connect.service
        echo 'Description=WiFi Captive Portal' | tee -a /etc/systemd/system/wifi-connect.service
        echo 'After=NetworkManager.service' | tee -a /etc/systemd/system/wifi-connect.service
        echo 'Before=hoobsd.service' | tee -a /etc/systemd/system/wifi-connect.service
        echo '' | tee -a /etc/systemd/system/wifi-connect.service
        echo '[Service]' | tee -a /etc/systemd/system/wifi-connect.service
        echo 'Type=oneshot' | tee -a /etc/systemd/system/wifi-connect.service
        echo 'ExecStart=/usr/local/sbin/wifi-connect-startup' | tee -a /etc/systemd/system/wifi-connect.service
        echo '' | tee -a /etc/systemd/system/wifi-connect.service
        echo '[Install]' | tee -a /etc/systemd/system/wifi-connect.service
        echo 'WantedBy=multi-user.target' | tee -a /etc/systemd/system/wifi-connect.service
    fi

    message "reloading systemd" "" "info"

    systemctl daemon-reload

    message "services cleaned" "" "ok"
}

repair_ssl_cacerts() {
    message "removing ssl cacert hacks" "certs, profile, sudo" "info"

    rm -f /etc/ssl/certs/cacert.pem

    if grep -q 'SSL_CERT_FILE' /etc/profile; then
        cat /etc/profile | sed 's,SSL_CERT_FILE=/etc/ssl/certs/cacert.pem,,g' | tee /etc/profile
        cat /etc/profile | sed 's,export SSL_CERT_FILE,,g' | tee /etc/profile
    fi

    if grep -q 'SSL_CERT_FILE' /etc/sudoers; then
        cat /etc/sudoers | sed 's,Defaults    env_keep += "SSL_CERT_FILE",,g' | tee /etc/sudoers
    fi

    message "ssl hacks removed" "" "ok"
}

install_packages() {
    message "upgrading system" "" "info"

    apt-get update --allow-releaseinfo-change
    dpkg --configure -a
    apt-get update 
    apt-get -y upgrade
    apt-get install -y curl

    message "repairing packages" "nodejs, yarn, hoobs" "info"

    curl -sk https://dl.hoobs.org/stable | bash -
    apt-get install -y nodejs yarn
    apt-get remove -y hoobsd hoobs-cli hoobs-gui hbs-vendor
    apt-get install -y nodejs yarn hoobsd hoobs-cli hoobs-gui hbs-vendor
    hbs install -p 80

    message "repairing packages" "helm" "info"

    apt-get install -y helm

    message "packages repaired" "" "ok"
}

install_watchdog() {
    message "installing packages" "watchdog" "info"

    apt-get install -y watchdog

    message "configuring watchdog to prevent and recover from crashes" "" "info"

    update-rc.d watchdog defaults

    echo "watchdog-device = /dev/watchdog" | tee /etc/watchdog.conf > /dev/null 2>&1
    echo "watchdog-timeout = 15" | tee -a /etc/watchdog.conf > /dev/null 2>&1
    echo "max-load-1 = 24" | tee -a /etc/watchdog.conf > /dev/null 2>&1
    echo "min-memory = 1" | tee -a /etc/watchdog.conf > /dev/null 2>&1
    echo "" | tee -a /etc/watchdog.conf > /dev/null 2>&1

    systemctl enable watchdog > /dev/null 2>&1

    message "watchdog configured" "" "ok"
}

clean_sources
clean_node_installs
clean_old_services

if grep -q 'http://mirrors.ocf.berkeley.edu/raspbian/raspbian/' /etc/apt/sources.list; then
    message "outdated berkley mirror detected" "" "wrn"
    message "reconfiguring raspbian sources" "raspbian.raspberrypi.org" "info"

    cat /etc/apt/sources.list | sed 's,http://mirrors.ocf.berkeley.edu/raspbian/raspbian/,http://raspbian.raspberrypi.org/raspbian/,g' | tee /etc/apt/sources.list

    message "raspbian sources fixed" "" "ok"
fi

if [ -f /etc/ssl/certs/cacert.pem ]; then
    message "ssl hacks detected" "" "wrn"

    repair_ssl_cacerts
fi

install_packages
install_watchdog

message "rebooting" "" "wrn"

shutdown -r now
